#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Sphinx configuration file for GatheRing documentation.
"""

import os
import sys
from datetime import datetime

# Add the project root to the Python path
sys.path.insert(0, os.path.abspath(".."))
sys.path.insert(0, os.path.abspath("../gathering"))

# -- Project information -----------------------------------------------------

project = "GatheRing"
copyright = f"{datetime.now().year}, Loc Cosnier"
author = "Loc Cosnier"

# The version info
version = "0.5.0"
release = "0.5.0"

# -- General configuration ---------------------------------------------------

# Sphinx extensions
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    "sphinx.ext.githubpages",
    "sphinx_copybutton",
    "sphinx_design",  # For grid cards
    "myst_parser",  # For Markdown support
]

# Add any paths that contain templates here
templates_path = ["_templates"]

# Source file suffixes
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# The master toctree document
master_doc = "index"

# List of patterns to ignore when looking for source files
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "archive"]

# The name of the Pygments style to use
pygments_style = "sphinx"

# -- Options for HTML output -------------------------------------------------

# The theme to use
html_theme = "sphinx_rtd_theme"

# Theme options
html_theme_options = {
    "canonical_url": "",
    "logo_only": False,
    "display_version": True,
    "prev_next_buttons_location": "bottom",
    "style_external_links": False,
    "style_nav_header_background": "#2980B9",
    # Toc options
    "collapse_navigation": False,
    "sticky_navigation": True,
    "navigation_depth": 4,
    "includehidden": True,
    "titles_only": False,
}

# Add any paths that contain custom static files
html_static_path = ["_static"]

# Custom CSS and JS files
html_css_files = [
    "custom.css",
]

html_js_files = [
    "lightbox.js",
]

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    "papersize": "letterpaper",
    "pointsize": "10pt",
}

# Grouping the document tree into LaTeX files
latex_documents = [
    (master_doc, "GatheRing.tex", "GatheRing Documentation", "GatheRing Team", "manual"),
]

# -- Options for manual page output ------------------------------------------

man_pages = [(master_doc, "gathering", "GatheRing Documentation", [author], 1)]

# -- Extension configuration -------------------------------------------------

# Intersphinx mapping
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
}

# Napoleon settings for Google/NumPy style docstrings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = True
napoleon_use_admonition_for_notes = True
napoleon_use_param = True
napoleon_use_rtype = True

# Autodoc settings
autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "special-members": "__init__",
    "undoc-members": True,
    "exclude-members": "__weakref__",
}

# Todo extension settings
todo_include_todos = True

# -- Options for internationalization ----------------------------------------

# The language for content autogenerated by Sphinx
language = "en"

# Directories for locale files (.po)
locale_dirs = ["locale/"]

# Use gettext_compact to keep translations separate per source file
gettext_compact = False

# Generate .pot files with unique IDs for better translation tracking
gettext_uuid = True

# Additional settings for translation workflow
gettext_additional_targets = ["literal-block", "image"]

# Copy button settings
copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True

# MyST parser settings for Markdown support
myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "html_image",
    "replacements",
    "smartquotes",
    "tasklist",
]

# Allow all heading levels in toctree
myst_heading_anchors = 3
